- name: installing the mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: stsrting the systemctl service for mysql
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: true
    state: started

- name: install python mysql dependencies

  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9 # pip3.11 if python version is 3.11

- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: print output
  ansible.builtin.debug:
    msg: "Output: {{mysql_connection_output}} "

- name: setup root password

  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connection_output.failed is true
